### PR TITLE
Adds kata explaining a curry function

### PR DESCRIPTION
**Pull request by kaeff**
I got curious about different alternatives for implementing currying. More and more people seem to be adopting functional-style JS - would you like to have katas in this direction?

### CODE REVIEW

**Comment by wolframkriesing** [comment]
cool. I am just not sure if the es6 folder is the right place, since it's a "normal" JS feature, not necessarily es6 only, right? What if we create the "functional-js" folder on the same level as the es6 folder? ...

**Comment by kaeff** [comment]
I've moved the kata.

BTW, I keep rebasing/squashing the changes while the pull requests are open. Ok?

**Comment by wolframkriesing** [comment]
Ahhh, sorry. Just wanted to merge it and I think if things like purescript, coffeescript, livescript, typescript will be added it might be better to put this kata into `javascript/functional` ... what do you think?

**Comment by kaeff** [comment]
Like so?

**Pull request merged**
