### PR TITLE
[fix] Scenario "'eliminate `arguments`!!!" ;

### PR DESCRIPTION
**Pull request by crisanlucid**
arguments - key is preserved 

rename with "args"

### CODE REVIEW

**Comment by wolframkriesing** [comment]
Hi, thanks for sending the PR, I just dont understand what problem this solves. Can you explain a little bit. thanks

**Comment by crisanlucid** [comment]
Sure, let me explain. In case of some javascript syntax error JavaScript fails.
I am trying to come with a solution which allow me to see how TDD is failed and not just a white screen

check the link bellow with white page where you cannot see the uses cases.
https://codepen.io/crisanlucid/pen/PVejmV

img: 
https://imgur.com/a/USXiV5y

**Comment by wolframkriesing** [comment]
unfortunately this clashes with the description of the test, which
explicitly states that "arguments" shall be removed, which tries to teach
that arguments is not needed anymore
if you try this inside tddbin the error shows up on the right side too

**Comment by crisanlucid** [comment]
Does the meaning of KATA js TDD to have javascript sintax error?

**Pull request closed without merging**
