### PR TITLE
Make kata "rename object key" red.

### PR DESCRIPTION
**Pull request by tobireif**

### CODE REVIEW

**Comment by wolframkriesing** [comment]
what would you think about changing it to this `const {x: newName} = {x: 1};` ?

**Comment by tobireif** [comment]
Yep, your suggestion is better, updated my PR for making the test red.

**Comment by wolframkriesing** [comment]
awesome that you have such a good eye for the details!!!

--
Kind regards / Saludos / Mit freundlichen Grüßen
Wolfram Kriesing, uxebu Co-Founder

kriesing@uxebu.com, mobile: +49 174 300 4595

ECMAScript6+React.js workshop http://meetu.ps/2Jds4D
Learn ES6, one kata a day http://es6katas.org

uxebu GmbH
Fraunhofer Straße 31e
86167 Augsburg

Amtsgericht Augsburg, Handelsregister HRB 28613
Directors: W. Kriesing, T. v. Klipstein

**Comment by tobireif** [comment]
Thx :)

**Pull request merged**
