### PR TITLE
remove the Symbol.iterator thing from the Symbol katas

### PR DESCRIPTION
**Pull request by ondblclick**
as Symbol.iterator thing will appear only in the next (37) kata

### CODE REVIEW

**Comment by wolframkriesing** [comment]
can u elaborate a little bit, I just cant follow what you mean yet, thanks

**Comment by ondblclick** [comment]
Yep, sorry. Walking through the katas, one by one, I've found out the thing you called a 'well-known symbol' isn't so well-known (in the 36 kata at least) as it is going to be described only in the next kata - in the 37 one.
And as I am lazy as hell, I've picked the easiest way - removing the test 🙈.
Few other options are:
# describe what Symbol.iterator is in the 36 kata; 
# use another 'well-known' symbol for this sample.

**Comment by wolframkriesing** [comment]
thanks for the input, I am thinking about it :)

**Comment by wolframkriesing** [comment]
I think `well-known` might be changed, maybe `predefined` is better

**Pull request merged**
