### PR TITLE
Fixes the related warnings.

### PR DESCRIPTION
**Pull request by tobireif**
Adding `yield` in order to fix the warnings. I hope that solution is OK for you.

### CODE REVIEW

**Comment by wolframkriesing** [comment]
this would then make the right side fail harder, and it would fail until ALL tests are fixed :(. tbh I am currently thinking of either turning off jshint warnings or including eslint (where the first might seem much simpler)
this is how it would fail if all yields were in there 
yield-fail-hard

-1 for this one

**Comment by tobireif** [comment]
Yes, I had added the "yield"s after I made the tests green / without running the unfixed tests.

**Comment by tobireif** [comment]
I agree, the right side does fail too hard, even fixing the first test doesn't help.

Regarding the warnings / turning off JSHint:
Perhaps these specific (and some other) warnings are correct and useful?
(If you keep ESLint or JSHint, probably ensure latest version.)

OK to keep the issue/PR closed, it's just an informative warning.

Or if you want I could add a comment (near the top / for all test cases), eg
`// (Not having a "yield" inside the generators is OK in the below test cases.)`

**Comment by wolframkriesing** [comment]
the comment would be ok.
not sure if necessary, since that would be the next step, reading the first lines in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function* does also not state anything about "yield", leaving it out hopefully reduces confusion. Or did it increase it for you?
I am always trying to strip out as much as possible to keep the focus as sharp as possible.

**Comment by tobireif** [comment]
OK to keep the kata as is.

**Pull request closed without merging**
